### ISSUE TITLE
Kleine Frage und Idee | Little Question and an idea

### ISSUE THREAD

**Issue by MTRNord** [0xSeb/CraftingKeys#1]
(English down below)
Ich hab gerade das Video gesehen und da kamen mir ein paar Fragen. 
1. Ist Mithilfe (Contribution) erwünscht bzw erlaubt und hast du dafür gewünschte Coding Standards?
2. Gibt es irgendwo ein Portal wo man sich über Crafting Keys (ordentlich) unterhalten kann? Eine Issue ist da nicht optimal.
3. Wird es eine Schnittstelle für weitere Mods geben sodass andere Modder ihre Mods mit dieser Funktion bereichern können?

---

I had seen just now your Video on Youtube and Have now some Questions.
1. Is Contrubution allowed and do you have a coding-standard for it?
2. Is there a Platform to discuss about Crafting Keys, because making an Issue for it seems not to be the best for it.
3. Is there a API like connection for other Mods planned? So that other people can build in the features.

mfg
MTRNord:D

**Comment by sebinside** [comment]
Hi,
1. Klar. Ich code open-source damit andere mithelfen oder was daraus lernen können. Es gibt noch diverse Verbesserungsmöglichkeiten - bevor du irgendwas angehst, frag aber am besten nach, nicht dass ich schon was anderes in eine andere richtung oder das selbe programmiert habe bzw. es vorhabe :)
2. Crafting Keys ist - trotz den laut GitHub 2000 Zeilen Code nicht grade umfassend. Deswegen hab ich nicht vor, sowas einzurichten. Alles, was notwendig ist, kann man auch per Mal besprechen; oder ich nenne es in den Videos.
3. Eine Schnittstelle hab ich noch nicht im Kopf. Dank dem umfassenden Refactoring wäre das aber ohne Probleme möglich; ich warte aber erstmal, wie es ankommt ;)

LG sebastian

**Comment by MTRNord** [comment]
Ok :) dann werde ich mir mal den Code ansehen und mal sehen wo ich helfen kann :D 
Ps: Coole Mod Idee ;)
