### ISSUE TITLE
Support of Dynious/VersionChecker

### ISSUE THREAD

**Issue by MTRNord** [0xSeb/CraftingKeys#12]
Hi is it possible to make it compatibel with [Dynious/VersionChecker](https://github.com/Dynious/VersionChecker) ? At this time the only big problem is that the jar files are hosted on mediaFire an mediafire don't provide real direct download links. So I opened an Issue for that at the ther repo to provide the ability of using mediafire links for it. (https://github.com/Dynious/VersionChecker/issues/83)  

My clear question is: Do you want to make it compatible with the Version checker or not? (If so I will open an Pull Request with everything that is needed)

Greeting by MTRNord :)

**Comment by Moritz30** [comment]
Mediafire DOES provide direct download links. Just edit the link...

```
     ---- On Mi, 10 Feb 2016 17:51:03 +0100  notifications@github.com  wrote ----Hi is it possible to make it compatibel with Dynious/VersionChecker ? At this time the only big problem is that the jar files are hosted on mediaFire an mediafire don't provide real direct download links. So I opened an Issue for that at the ther repo to provide the ability of using mediafire links for it. (Dynious/VersionChecker#83)  
```

My clear question is: Do you want to make it compatible with the Version checker or not? (If so I will open an Pull Request with everything that is needed)
Greeting by MTRNord :)

**Comment by MTRNord** [comment]
@Moritz30 all links that you get with right click and copy link will EXPIRE after x days

**Comment by MTRNord** [comment]
EDIT: example implementation of the support can you find here: https://github.com/MTRNord/CraftingKeys/tree/patch-3

**Comment by sebinside** [comment]
Mediafire ist nur eine temoräre Lösung. Früher oder später werde ich die JARs selbst hosten. Andere Funktionen wie API Support sind grade wichtiger... oder mal allgemein ein Update auf 1.8.9 und bald 1.9 =D

**Comment by MTRNord** [comment]
OK :)
