### ISSUE TITLE
Fehler mit 1.8

### ISSUE THREAD

**Issue by MTRNord** [0xSeb/CraftingKeys#4]
Wenn man die ConfigGUI.java datei auf die 1.8 version aktualisiert, also an der stelle "new ConfigElement<java.util.List<net.minecraftforge.fml.client.config.IConfigElement>>" einträgt bekomme ich den Fehler "Error:(47, 34) java: type net.minecraftforge.common.config.ConfigElement does not take parameters" beim bauen des Mods. Ist das schon auf deiner TODO list zum fixen? 

Habe allerding als ich einfach das in den spitzen klammern entfernt habe keine veränderungen bemerkt.

**Comment by sebinside** [comment]
Die 1.8 steht noch gar nicht auf meiner TODO-Liste. Änderungen werden auch beim Packet Handling notwendig werden. Deswegen will ich erstmal eine vollständig lauffähige 1.7-Version haben, bevor ich anfange, die Sachen auf 1.8 anzupassen ;)

**Comment by MTRNord** [comment]
ok :) ich mache mir mal lokal bzw bei dem fork mal eine 1.8 anpassung :) dann kann ich dich wenn nötig so zu sagen über größere Probleme vorwarnen die später dir Probleme machen könnten

**Comment by sebinside** [comment]
Okay, das wird vor allem beim Packet Handling und bei der neuen GUI interessant :+1:
