### ISSUE TITLE
Doppelte Einträge in den Tastaturbelegungs-Einstellungen

### ISSUE THREAD

**Issue by MTRNord** [0xSeb/CraftingKeys#6]
Seit dem Pull Request #5  sind nun in den Einstellungen unter den Tastaturbelegungen alle Felder doppelt vorhanden wenn das Spiel auf Deutsch eingestellt ist. Da scheint etwas kaputt gemacht worden zu sein.

**Comment by blackgamelp** [comment]
die CaftingKeys Config ist dann noch bei dir die alte, wenn die einmal neu erstellt wird, ist alles in ordnung

Denn jede Property in der Config wird dann in den Einstellungen als ein Einstellungswert genommen, da ich aber die Property Keys geändert habe werden die Doppelt angezeigt.

**Comment by MTRNord** [comment]
Jetzt geht es :) danke

**Comment by sebinside** [comment]
Ja, das kommt immer, wenn man die IDs der Config-Einträge ändert. Einfach die Config-Datei einmal löschen ;)
